nuoian:
  file:
    visit-path: xxxxxx
    ftp:
      user: nuoian
      password: nuoian
      host: 127.0.0.1
      port: 21
  thread:
    core-pool-size: 16
    max-pool-size: 64
    queue-capacity: 999
    keep-alive-seconds: 60
    await-termination-seconds: 60
    thread-name-prefix: nuoian-async-
    wait-for-tasks-to-complete-on-shutdown: true
